//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniotech_LedTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1080")]
        public short CH1_VALUE {
            get {
                return ((short)(this["CH1_VALUE"]));
            }
            set {
                this["CH1_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public short CH2_VALUE {
            get {
                return ((short)(this["CH2_VALUE"]));
            }
            set {
                this["CH2_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1497")]
        public short CH3_VALUE {
            get {
                return ((short)(this["CH3_VALUE"]));
            }
            set {
                this["CH3_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public short CH4_VALUE {
            get {
                return ((short)(this["CH4_VALUE"]));
            }
            set {
                this["CH4_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("121")]
        public float CH1_PF_MIN {
            get {
                return ((float)(this["CH1_PF_MIN"]));
            }
            set {
                this["CH1_PF_MIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("189")]
        public float CH1_PF_MAX {
            get {
                return ((float)(this["CH1_PF_MAX"]));
            }
            set {
                this["CH1_PF_MAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28.8")]
        public float CH2_PF_MIN {
            get {
                return ((float)(this["CH2_PF_MIN"]));
            }
            set {
                this["CH2_PF_MIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33")]
        public float CH2_PF_MAX {
            get {
                return ((float)(this["CH2_PF_MAX"]));
            }
            set {
                this["CH2_PF_MAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("174")]
        public float CH3_PF_MIN {
            get {
                return ((float)(this["CH3_PF_MIN"]));
            }
            set {
                this["CH3_PF_MIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("241.5")]
        public float CH3_PF_MAX {
            get {
                return ((float)(this["CH3_PF_MAX"]));
            }
            set {
                this["CH3_PF_MAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61")]
        public float CH4_PF_MIN {
            get {
                return ((float)(this["CH4_PF_MIN"]));
            }
            set {
                this["CH4_PF_MIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90.3")]
        public float CH4_PF_MAX {
            get {
                return ((float)(this["CH4_PF_MAX"]));
            }
            set {
                this["CH4_PF_MAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float CH1_PF_ERROR {
            get {
                return ((float)(this["CH1_PF_ERROR"]));
            }
            set {
                this["CH1_PF_ERROR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float CH2_PF_ERROR {
            get {
                return ((float)(this["CH2_PF_ERROR"]));
            }
            set {
                this["CH2_PF_ERROR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float CH3_PF_ERROR {
            get {
                return ((float)(this["CH3_PF_ERROR"]));
            }
            set {
                this["CH3_PF_ERROR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float CH4_PF_ERROR {
            get {
                return ((float)(this["CH4_PF_ERROR"]));
            }
            set {
                this["CH4_PF_ERROR"] = value;
            }
        }
    }
}
